
import { Category, Store, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: 'games', label: 'Games', icon: 'sports_esports', colorClass: 'bg-blue-100 text-blue-600' },
  { id: 'construcao', label: 'Construção', icon: 'construction', colorClass: 'bg-orange-100 text-orange-600' },
  { id: 'eletro', label: 'Eletro', icon: 'kitchen', colorClass: 'bg-green-100 text-green-600' },
  { id: 'roupas', label: 'Roupas', icon: 'apparel', colorClass: 'bg-purple-100 text-purple-600' },
  { id: 'utilidades', label: 'Utilidades', icon: 'cooking', colorClass: 'bg-yellow-100 text-yellow-600' },
  { id: 'pets', label: 'Pets', icon: 'pets', colorClass: 'bg-red-100 text-red-600' },
];

export const MOCK_STORES: Store[] = [
  {
    id: '1',
    name: 'Mercadinho Central',
    logo: 'https://picsum.photos/seed/store1/100',
    cover: 'https://picsum.photos/seed/cover1/800/400',
    rating: 4.8,
    reviewsCount: 120,
    deliveryTime: '30-45 min',
    deliveryFee: 5.9,
    category: 'Mercado',
    isOpen: true,
  },
  {
    id: '2',
    name: 'ConstruTudo',
    logo: 'https://picsum.photos/seed/store2/100',
    cover: 'https://picsum.photos/seed/cover2/800/400',
    rating: 4.5,
    reviewsCount: 85,
    deliveryTime: '60 min',
    deliveryFee: 15.0,
    category: 'Construção',
    isOpen: true,
  },
  {
    id: '3',
    name: 'GameZone',
    logo: 'https://picsum.photos/seed/store3/100',
    cover: 'https://picsum.photos/seed/cover3/800/400',
    rating: 4.9,
    reviewsCount: 210,
    deliveryTime: '20-30 min',
    deliveryFee: 0,
    category: 'Eletrônicos',
    isOpen: true,
  },
  {
    id: '4',
    name: 'Moda Jarinu',
    logo: 'https://picsum.photos/seed/store4/100',
    cover: 'https://picsum.photos/seed/cover4/800/400',
    rating: 4.7,
    reviewsCount: 45,
    deliveryTime: '40 min',
    deliveryFee: 7.5,
    category: 'Vestuário',
    isOpen: false,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    storeId: '2',
    name: 'Cimento Votoran 50kg Obras Estruturais',
    description: 'Cimento de alta resistência indicado para obras estruturais.',
    price: 35.0,
    originalPrice: 38.0,
    image: 'https://picsum.photos/seed/p1/400',
    category: 'Construção',
    isPromotion: true,
  },
  {
    id: 'p2',
    storeId: '3',
    name: 'Controle PS5 DualSense Branco',
    description: 'Controle sem fio DualSense para PlayStation 5.',
    price: 449.9,
    originalPrice: 499.0,
    image: 'https://picsum.photos/seed/p2/400',
    category: 'Games',
    isPromotion: true,
  },
  {
    id: 'p3',
    storeId: '5',
    name: 'Fritadeira Elétrica Air Fryer 4L',
    description: 'Fritadeira sem óleo com capacidade de 4 litros.',
    price: 399.0,
    image: 'https://picsum.photos/seed/p3/400',
    category: 'Eletro',
  },
  {
    id: 'p4',
    storeId: '4',
    name: 'Camiseta Básica Algodão Premium',
    description: 'Camiseta masculina 100% algodão, toque macio.',
    price: 49.9,
    image: 'https://picsum.photos/seed/p4/400',
    category: 'Roupas',
    isNew: true,
  },
];
